services:

  app:
      container_name: library_system_backend
      build: .  
      env_file:
        - .env
      depends_on:
        - db
  db:
    image: postgres:18-alpine
    container_name: library_system_database
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - ${DB_DOCKER}:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
